version: "3"

volumes:
  back-data:
    driver: local

services:
  back-db:
    image: postgres
    env_file:
      - back/.env
    ports:
      - "5432:5432"
    volumes:
      - back-data:/var/lib/postgresql/data
  back:
    restart: on-failure
    build:
      context: ./back
    deploy:
      replicas: 2
  nginx:
    restart: on-failure
    build: nginx
    ports:
      - "8001:80"